NAME = "Windows-Server-2019"
BOX_NAME = "StefanScherer/windows_2019"

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 60
  config.vm.communicator = "winrm"

  config.vm.define NAME do |vm_windows|
    vm_windows.vm.box = BOX_NAME
    vm_windows.vm.hostname = "windowsserver2019"

    vm_windows.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.cpus = 2
      v.memory = 4096
      v.customize ["modifyvm", :id, "--hwvirtex", "on"]
      v.customize ["modifyvm", :id, "--nic2", "bridged", "--bridgeadapter2" , "Realtek PCIe GbE Family Controller", "--cableconnected1", "on"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.customize ["modifyvm", :id, "--nictype3", "82540EM"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
  end
end

